### ISSUE TITLE
Component state reset if screen component changes

### ISSUE THREAD

**Issue by njdancer** [react-navigation/navigation-ex#166]
### Current Behavior

I'm trying to pass props into my screen components by wrapping them in an arrow function with props provided. Whenever this wrapper function is recreated react navigation unmount and then remounts the component forcing its state to reset.

### Expected Behavior

There are probably reasons it needs to work this way but I'm unsure of a way to workaround the current behaviour. My understanding of react would suggest that because this function will render out to the same component tree and never be removed from the virtual dom it shouldn't lose its state. If this is intended behaviour ideally I would like some kind of flag to disable it if possible.

### How to reproduce

In the following reproduction the root component is re-rendered every 5 seconds which causes the inline function to be recreated and ultimately the component to unmount and remount. This can be confirmed by entering text into the text-field which upon re-render disappears. This can be alleviated in this instance with useCallback however when any dependencies change the same occurs so even if I hoisted the necessary state out of this component I have the same issue when trying to pass it in.

https://snack.expo.io/@njdancer/e52848

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^5.0.0-alpha.19
| react-native     | 0.59
| expo             | 35

**Comment by satya164** [comment]
> My understanding of react would suggest that because this function will render out to the same component tree and never be removed from the virtual dom it shouldn't lose its state

You're creating a component inside render. Every time `() => <HomeScreen test="test" />` is called, it'll return a new component. React doesn't preserve state between 2 different components.

React Navigation supports an alternative undocumented way to defined a render function instead of a component:

```js
<Screen name="Home">{() => <HomeScreen test="test" />}</Screen>
```

**Comment by satya164** [comment]
> My understanding of react would suggest that because this function will render out to the same component tree and never be removed from the virtual dom it shouldn't lose its state

You're creating a component inside render. Every time `() => <HomeScreen test="test" />` is called, it'll return a new component. React doesn't preserve state between 2 different components.

React Navigation supports an alternative undocumented way to defined a render function instead of a component:

```js
<Screen name="Home">{() => <HomeScreen test="test" />}</Screen>
```

However, you need to ensure that your `HomeScreen` component doesn't re-render unnecessarily by wrapping it in `React.memo` manually to avoid perf issues. Since you're not passing a component, we can't do it automatically.

A better approach is to use React context to provide state to screens.

**Comment by njdancer** [comment]
@satya164 Thanks, that is perfect. I think I was getting confused about the difference between a render prop and just passing the component. I see you've already updated the docs which Is fantastic.
https://reactnavigation.org/docs/en/next/hello-react-navigation.html#passing-additional-props

Thanks for your quick response. Really loving v5.
