### ISSUE TITLE
How to access NavigationAction from event?

### ISSUE THREAD

**Issue by Bene8493** [react-navigation/navigation-ex#176]
In react-navigation v3 we used something like this to call `resetSearch` when the user comes back to a screen:
```javascript
this.props.navigation.addListener("willFocus", (payload: NavigationEventPayload) => {
            if (payload.action.type !== NavigationActions.BACK) {
                resetSearch();
            }
        });
```

I switched to react-navigation v5 and now payload has the type:
```javascript
payload: {
    readonly type: "focus";
    readonly defaultPrevented: boolean;
    preventDefault(): void;
}
```

How can I call `resetSearch` when coming back to this screen?

**Comment by satya164** [comment]
Looks like what you want is to call `resetSearch` when the screen is focused again after it was blurred, not necessarily on `NavigationActions.BACK` because the screen can come into focus in a lot of ways (e.g. other actions such as pop or reset). Relying on `NavigationActions.BACK` is fragile.

To achieve what you want: you could call `resetSearch` on `blur` event which would give you the similar result, or set some variable on `blur` and check it on `focus`:

```js
const wasBlurred = React.useRef(false);

useEffect(() => {
  return navigation.addListener('blur', () => wasBlurred.current = true)
}, []);

useEffect(() => {
  return navigation.addListener('focus', () => {
    if (wasBlurred.current) {
      resetSearch();
      wasBlurred.current = false;
    }
  })
}, []);
```
