### ISSUE TITLE
[v5] Some thoughts on onFocusEffect API

### ISSUE THREAD

**Issue by lachenmayer** [react-navigation/navigation-ex#270]
Hi there, I've converted our app to react-navigation v5, and so far it's been a real breeze - loving the new API, especially being able to type-check `navigate` calls, great job!

One thing that was a bit confusing initially is how `onFocusEffect` works - this isn't necessarily a bug, but I thought it'd be useful to give this feedback now, before the API is totally stable. Feel free to ignore if you're set on the current API :)

TL;DR:

- You currently need to return `undefined` in the `onFocusEffect` callback if you don't want to return a cleanup function.
- `useFocusEffect` triggers on every render if focused, it would be nice if you could control this without having to use `React.useCallback`

## Current Behavior

In our code using react-navigation v4, we have the following pattern in a couple of places:

```ts
const { data, refetch } = useQuery(...)
navigation.addListener('willFocus', () => refetch())
```

In v5, I initially replaced this with the following:

```ts
const { data, refetch } = useQuery(...)
useFocusEffect(() => {
  refetch()
  return undefined // this is required, see below!
})
```

The [`useFocusEffect` docs](https://reactnavigation.org/docs/en/next/use-focus-effect.html) say:

> The `useFocusEffect` is analogous to React's `useEffect` hook. The only difference is that it runs on focus instead of render.

Now, what I expected "runs on focus instead of on render" to mean is that `refetch` would be called (once) when the screen is focused. Instead, that screen kept flickering between the loading state and the loaded state.

---

Separately, I had to add `return undefined` to the `useFocusEffect` callback because it has the following type:

```ts
// from react-navigation
type EffectCallback = (() => undefined) | (() => () => void);
```

I believe it would be better to use the `EffectCallback` definition that ships with React's TypeScript definition:

```ts
// from @types/react
type EffectCallback = () => (void | (() => void | undefined));
```

This would allow removing the unnecessary return statement. This one should be an easy fix :)

## Expected Behavior

Properly re-reading the docs, I found that this is actually the expected behavior, ie. the callback gets triggered every time the component re-renders while focused. The docs suggest to use `React.useCallback` to control how often the callback should be triggered. Changing the call to the following did indeed work as expected:

```ts
useFocusEffect(
  React.useCallback(() => {
    refetch()
    return undefined
  }, [])
)
```

I feel like that's a lot of code for something as simple as "refetch every time the screen is focused". 

In our codebase, I count over 50 uses of React's built-in `useEffect` hook, and every single one of those calls uses the array argument, because we always want to either (a) perform an effect on component mount (ie. as a replacement to `componentDidMount`), or (b) whenever some value changes (ie. as a replacement to `componentDidUpdate`). As such, I found it quite weird that you have to add `React.useCallback` to get that same behavior using `useFocusEffect`.

## Proposed changes

I propose changing `useFocusEffect` to add the array of dependencies as an optional second argument, so that all of the following are valid:

```ts
// This should refetch once the screen is focused.
useFocusEffect(() => {
  refetch()
}, [])

// This should subscribe once the screen is focused, and unsubscribe once the screen is unfocused.
useFocusEffect(() => {
  subscribe()
  return () => unsubscribe()
}, [])

// Same behavior as before, ie: run on every render while focused.
useFocusEffect(() => {
  doSomething()
})
```

This would make `useFocusEffect` work exactly like `useEffect`, except that it only runs when the screen is focused, as advertised :)

## How to reproduce

(I hope this doesn't need a repro, let me know if you'd like one!)

## Your Environment

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | both |
| @react-navigation/native       | 5.0.0-alpha.27 |
| react-native                   | whatever Expo 36 ships with |
| expo                           | 36.0.1 |
| node                           | 12 |
| npm or yarn                    | npm |

**Comment by satya164** [comment]
Thanks for opening the issue.

> Now, what I expected "runs on focus instead of on render" to mean is that refetch would be called (once) when the screen is focused. Instead, that screen kept flickering between the loading state and the loaded state.

The statement definitely needs to be reworked. It should be "runs if the screen is currently focused." instead of "runs on focus". It's analogous to `useEffect` in the sense that `useEffect` will run on mount and cleanup on unmount with empty deps, with deps it runs whenever the deps change. Similarly `useFocusEffect` will run on focus and cleanup on blur with empty deps, with deps it runs whenever the deps change if the screen is focus (mount is equivalent to focus).

> I believe it would be better to use the EffectCallback definition that ships with React's TypeScript definition

Good catch. Can you open a separate issue for that? I think React's typeScript definition is wrong in this case. The return type `void` allows anything to be returned. But it's not valid to return anything other than `undefined`. In fact, if you return something other than undefined, React prints a warning about it in runtime even if you don't have a TS error.

So `undefined` should be the correct type here, but it seems that TypeScript doesn't have a good way to type it properly, so we'll need to settle with `void` if we can't figure out a better way.

> I propose changing useFocusEffect to add the array of dependencies as an optional second argument

We have considered this API before arriving on the current API. The problem with accepting dependency array is that it doesn't work with the official hooks ESLint plugin for third-party hooks (at least without any setup that most users won't do). Personally I consider the ESLint plugin pretty important to keep the dependency array up-to-date and we don't want to not support it in the default API.

Currently, the only way to support it is to use `useCallback`. I asked React team's opinion about it, and this is also what they recommend: https://twitter.com/dan_abramov/status/1156168847428395008
