### ISSUE TITLE
[Question] How to resetRoot with animation?

### ISSUE THREAD

**Issue by hyochan** [react-navigation/navigation-ex#295]
**Expected Behavior**
If I reset root like below, I want the screen appear from the right.
```
      navigation.resetRoot({
        index: 0,
        routes: [{ name: 'MainStack' }],
      });
```

If I reset root like below, I want to screen to appear from the left.
```
      navigation.resetRoot({
        index: 0,
        routes: [{ name: 'AuthStack' }],
      });
```

How would this be possible? Previously, we used `StackViewStyleInterpolator`
```
import StackViewStyleInterpolator from 'react-navigation/src/views/StackView/StackViewStyleInterpolator';
```
**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | both
| @react-navigation/native       | 5.0.0-alpha.21
| @react-navigation/stack        | 5.0.0-alpha.46
| react-native-gesture-handler   | 1.5.0
| react-native-safe-area-context | 0.6.0
| react-native-screens           | 2.0.0-alpha.12
| react-native                   | https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz
| expo                           | 36.0.2
| node                           |  12 lts
| npm or yarn                    | yarn

**Comment by hyochan** [comment]
Looks like `resetRoot` have been removed in the recent version. I don't feel forcing users to use `context api` for auth-flow just to use `react-navigation` is right tough.
https://reactnavigation.org/docs/en/next/auth-flow.html

**Comment by satya164** [comment]
> Looks like `resetRoot` have been removed

`resetRoot` isn't removed. It's now only present in the navigation object obtained from the `ref` of the container because that's where it makes sense.

Each screen's `navigation` object still has a `reset` method which lets you reset the particular navigator's state.

> I don't feel forcing users to use `context api` for auth-flow just to use `react-navigation` is right tough

It's an example. You can use any state management library if you don't want to use context directly. Context is used in the example because it's the most convenient way without requiring a third party library.

You can also use any pattern to handle auth flow, `reset`, `replace` etc. are still available. You can even use the stack navigator like a switch navigator if you just use `replace`.

Conditionally rendering screens is the recommended approach because that's the safest and easiest way to handle auth. By controlling which screens are rendered based on your app's logged in state, you eliminate many edge cases. It prevents the navigation state being out of sync with your logged in state since it's impossible to incorrectly open a screen which shouldn't be accessible (e.g. if you restore navigation state and token is not valid anymore, user won't end up on the home screen which will be incorrect).
