### ISSUE TITLE
Cannot pass function to component

### ISSUE THREAD

**Issue by Elias-Graf** [react-navigation/navigation-ex#302]
First of all, I'm kind of new to this, and I'm not sure if I missed it in the docs or something so don't be mad if I did okay :D?

So I'm trying to pass some functions to a component and get the error: `We found non-serializable values in the navigation state, which can break usage such as persisting and restoring state. This might happen if you passed non-serializable values such as function, class instances etc. in params. If you need to use functions in your options, you can use 'navigation.setOptions' instead.`. Which sounds sensible given that we/you want to have state persistence/deep linking. But how do you actually pass functions if you **need** to? `this.props.navigation.setOptions` seems to only reveal stuff from the navigation component like: `animationEnabled`.

And yes I really **need** to pass functions as my component offers the ability to implement custom sorting, filtering and rendering methods.

Also, I'm using typescript so take this into account when answering.

Thanks in advance for the response.

Edit:
Reading this again I think that this is probably not a bug but a question for (for example) StackOverflow. Though, this version is so new that I don't think I will get any answers there as none trivial questions rarely get answered anyways.

**Comment by satya164** [comment]
Instead of passing a function to sort, you can pass some information on how to sort, for example. e.g - instead of a function `sortByType`, you can pass something like `sortBy: 'type'` and implement the sort function in the target screen instead. It'll probably be more complex in your case, but you get the idea.

If your sorting is fully custom and this is not possible, you have 2 options:

1. Store those functions somewhere else, like in a context and pass name of the function in params. Then your screen can get the function from context by the name.
2. Ignore the warning and ensure to handle this case when restoring state of you're persisting it. For deep linking, `useLinking` accepts custom `stringify` and `parse` options. Or if you don't care about deep linking it persistence, then just suppress the warning.

**Comment by Elias-Graf** [comment]
I get what you're saying. Maybe it would be useful to create something like a `depended` route that cannot be opened in `deepLinking` and so on (my component also features a `onDone` method and is built around generics, much like the `react-native`s flatList)?

**Comment by arberK** [comment]
@satya164  What would be the case if we want to pass a stream?  I have a case where I pass a webRTC stream to a new screen.
