### ISSUE TITLE
`route.params` can be undefined

### ISSUE THREAD

**Issue by janicduplessis** [react-navigation/navigation-ex#76]
I think we should make sure this is never undefined even when passing no params to a route navigation. Example `navigation.navigate('otherScreen')` -> in otherScreen -> `route.params // = {}`.

**Comment by osdnk** [comment]
I'm supportive for `getParam` on `route`

**Comment by satya164** [comment]
routes need to be serialisable objects. I don't want a method on `route`

regarding `route.params` always being an object, we can do this in the built-in routers, but it's not something we can enforce for custom routers, so it'll be confusing imo. with optional chaining operator coming soon, it won't be a problem imo.

if you use typescript, you won't be able to `navigate` without passing params if the screen requires them. there is also `initialParams` prop on the screen component which you can use to provide fallback params.

**Comment by osdnk** [comment]
why do you need `route` to be serialisable? Because of deeplinking? Can't we omit this method?

**Comment by satya164** [comment]
because adding a method will add significant overhead to routers. dealing with pojos is much easier. instead of a method on object, something like `get` from lodash will do the job without adding any overhead.

**Comment by janicduplessis** [comment]
After migrating a lot of screens, it is an annoyance, I feel like adding a default to an empty object (even if just in the built in routers) makes params a lot easier to use. I agree that upcoming js syntax will help but since it isn't available at the moment it doesn't help (at least for TS).

I also think that when using vanilla js this can be an easy source of bugs since you can't know whether you need to null check params or not.

**Comment by janicduplessis** [comment]
Here's an example migration

```js
  // Before
  const email = useTextInput(navigation.getParam('email', ''));

  // After
  const email = useTextInput(
    route.params != null && route.params.email != null
      ? route.params.email
      : '',
  );
```

**Comment by satya164** [comment]
It's definitely an annoyance, and makes sense not to use lodash for this use case, but we can also our own `getParam` helper to ease the migration, it doesn't need to be built-in:

```js
const getParam = (route, param, default) => {
  const params = route.params;

  if (params && paramName in params) {
    return params[paramName];
  }

  return defaultValue;
};

// ...

const email = useTextInput(getParam(route, 'email', ''));
```

Technically it's not possible (or at least it'll be incorrect) to add a `getParam` method without changing `navigation` object often, which all nested screens since they inherit from parent navigation object, and causes inconvenience for doing things in hooks with dep array which people are confused about how to handle. A `getParam` on `route` will add significant overhead in routers to make sure this method always returns up-to-date value when params changes. So we can't add a `getParam` method.

Though imo if the params can be empty and we need default values for params, we should provide fallback params:

```js
initialParams={{ email: '' }}
```

This allows you to just write `route.params.email` everywhere instead having to do a `getParam` and provide a default value every time we need to access the params, which is more convenient. Personally this is what I'd prefer when we need fallback params. Why won't this work for you?

> I agree that upcoming js syntax will help but since it isn't available at the moment it doesn't help (at least for TS)

I agree that it's not available currently, but it's stage-3 already and planned for TypeScript 3.7: https://github.com/microsoft/TypeScript/issues/16. The navigation library is still alpha and I wanna avoid adding a method that will become obsolete when we release stable.

> I also think that when using vanilla js this can be an easy source of bugs since you can't know whether you need to null check params or not.

I think when not using types, we already need to remember how the object looks, so it's not very different here. Though if screen accesses params and they can be empty, imo user should provide fallback params.

Anyway, I just realised that we actually don't need the router to handle default empty object for params and we can handle it in core, so it'll be easier to add. We can make params empty object by default. Though it doesn't quite handle your case, so imo you should either provide fallback params or use own helper.

**Comment by satya164** [comment]
nvm. it won't be straightforward. a lot of work is needed on router's side to actually have ensure that there's an empty object available for params.

**Comment by janicduplessis** [comment]
`initialParams` seems like a good compromise for now
